server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphQL
    username: root
    password: Ranjeet@97
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  graphql:
    graphiql:
      enable: true
