"""
Indicates an Input Object is a OneOf Input Object.
"""
directive @oneOf on INPUT_OBJECT

"""
This directive allows results to be deferred during execution
"""
directive @defer(
  """
  Deferred behaviour is controlled by this argument
  """
  if: Boolean! = true

  """
  A unique label that represents the fragment being deferred
  """
  label: String
) on FRAGMENT_SPREAD | INLINE_FRAGMENT

"""
This directive disables error propagation when a non nullable field returns null for the given operation.
"""
directive @experimental_disableErrorPropagation on QUERY | MUTATION | SUBSCRIPTION

type Mutation {
  createUser(
    name: String
    email: String
    phoneNo: String
    password: String
  ): User
  deleteUserById(userId: ID!): Boolean
  createOrder(
    orderDetails: String
    address: String
    price: Int
    amount: Float
    userId: ID!
  ): Order
  deleteOrderById(orderId: ID!): Boolean
  updateUser(
    userId: ID!
    name: String
    email: String
    phoneNo: String
    password: String
  ): User
  updateOrder(
    orderId: ID!
    orderDetails: String
    address: String
    price: Int
    amount: Float
  ): Order
}

type Order {
  orderId: ID!
  orderDetails: String
  address: String
  price: Int
  amount: Float
  user: User
}

type Query {
  getAllUser: [User]
  getUserById(userId: ID!): User
  getOrderById(orderId: ID!): Order
  getAllOrder: [Order]
}

type User {
  userId: ID!
  name: String
  email: String
  phoneNo: String
  password: String
  orders: [Order]
}
